frame = "none"
maximized = true
tabs = false

[font]
size = 12
hinting = "full"
edging = "antialias"

[[font.normal]]
family = "JetBrains Mono"
style = "Regular"

[[font.italic]]
family = "JetBrains Mono"
style = "Italic"

[[font.bold]]
family = "JetBrains Mono"
style = "Bold"

[[font.bold_italic]]
family = "JetBrains Mono"
style = "Bold Italic"
