show_help = false
show_preview = false
show_tabs = false
enter_accept = true
exit_mode = "return-query"
filter_mode_shell_up_key_binding = "directory"
history_filter = [
    "^git status$",
    "^git diff$",
    "^g status$",
    "^g diff$",
    "^l$",
    "^ls$",
    "^z$",
    "^cd$",
    "^pwd$",
    "^clear$",
    "^exit$",
    "^cls$",
    "^z -$",
    "^z ..$",
    "^cd -$",
    "^cd ..$",
]

[search]
filters = ["global", "directory"]
