local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable",
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require('lazy').setup({
  '0oAstro/dim.lua',
  'AndrewRadev/sideways.vim',
  'AndrewRadev/splitjoin.vim',
  'JoosepAlviste/nvim-ts-context-commentstring',
  'L3MON4D3/LuaSnip',
  'RRethy/nvim-treesitter-endwise',
  'RRethy/vim-illuminate',
  'airblade/vim-rooter',
  'akinsho/bufferline.nvim',
  'akinsho/toggleterm.nvim',
  'andymass/vim-matchup',
  'b0o/schemastore.nvim',
  'ckolkey/ts-node-action',
  'danymat/neogen',
  'easymotion/vim-easymotion',
  'farmergreg/vim-lastplace',
  'folke/lsp-colors.nvim',
  'folke/todo-comments.nvim',
  'folke/tokyonight.nvim',
  'folke/trouble.nvim',
  'folke/which-key.nvim',
  'github/copilot.vim',
  'glepnir/lspsaga.nvim',
  'hrsh7th/cmp-buffer',
  'hrsh7th/cmp-calc',
  'hrsh7th/cmp-cmdline',
  'hrsh7th/cmp-nvim-lsp',
  'hrsh7th/cmp-path',
  'hrsh7th/nvim-cmp',
  'ilyachur/cmake4vim',
  'jayp0521/mason-null-ls.nvim',
  'jghauser/mkdir.nvim',
  'jiangmiao/auto-pairs',
  'jose-elias-alvarez/null-ls.nvim',
  'jose-elias-alvarez/nvim-lsp-ts-utils',
  'junegunn/vim-easy-align',
  'kana/vim-textobj-user',
  'leafOfTree/vim-vue-plugin',
  'leoluz/nvim-dap-go',
  'lervag/vimtex',
  'lewis6991/gitsigns.nvim',
  'lewis6991/impatient.nvim',
  'machakann/vim-highlightedyank',
  'mfussenegger/nvim-dap',
  'mfussenegger/nvim-dap-python',
  'mg979/vim-visual-multi',
  'michaeljsmith/vim-indent-object',
  'nelstrom/vim-visual-star-search',
  'neovim/nvim-lspconfig',
  'numToStr/Comment.nvim',
  'nvim-lualine/lualine.nvim',
  'nvim-tree/nvim-tree.lua',
  'nvim-tree/nvim-web-devicons',
  'nvim-treesitter/nvim-treesitter-textobjects',
  'nvim-treesitter/playground',
  'preservim/vim-markdown',
  'ray-x/lsp_signature.nvim',
  'rcarriga/nvim-dap-ui',
  'rhysd/clever-f.vim',
  'saadparwaiz1/cmp_luasnip',
  'sickill/vim-pasta',
  'svermeulen/vim-cutlass',
  'svermeulen/vim-subversive',
  'tommcdo/vim-exchange',
  'tpope/vim-abolish',
  'tpope/vim-eunuch',
  'tpope/vim-fugitive',
  'tpope/vim-repeat',
  'tpope/vim-rhubarb',
  'tpope/vim-sleuth',
  'tpope/vim-surround',
  'vim-test/vim-test',
  'wbthomason/packer.nvim',
  'williamboman/mason-lspconfig.nvim',
  'williamboman/mason.nvim',
  'windwp/nvim-ts-autotag',
  'xuhdev/vim-latex-live-preview',
  { 'iamcco/markdown-preview.nvim',             build = function() vim.fn['mkdp#util#install']() end },
  { 'michaelb/sniprun',                         build = 'bash ./install.sh' },
  { 'nvim-telescope/telescope-fzf-native.nvim', build = 'make' },
  { 'nvim-telescope/telescope.nvim',            dependencies = { 'nvim-lua/plenary.nvim' } },
  { 'whatyouhide/vim-textobj-xmlattr',          dependencies = { 'kana/vim-textobj-user' } },
  { 'thinca/vim-textobj-between',               dependencies = { 'kana/vim-textobj-user' } },
  { 'kana/vim-textobj-entire',                  dependencies = { 'kana/vim-textobj-user' } },
  { 'nvim-treesitter/nvim-treesitter',          build = ':TSUpdate' }
})
